# Generated by Django 5.0 on 2024-02-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_remove_department_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courses',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='courses',
            new_name='name',
        ),
    ]
