# Generated by Django 5.0 on 2024-02-06 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_material_person_address_person_age_person_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
    ]
