# Generated by Django 5.0 on 2024-02-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_remove_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
