# Generated by Django 5.0 on 2024-02-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_person_age_person_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='materials_provide',
        ),
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mail_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='purpose',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
